### ISSUE TITLE
MKFetcherError

### ISSUE THREAD

**Issue by LordWurstebrot** [matoH12/checkmk-nextcloud#4]
Hi @matoH12

first of all thanks for providing this plugin!

When I try to use the special agent I get the following error:

`Fetching 'agent'...
Failed: Failed to fetch data from subdomain.domain.de: Error(MKFetcherError('Agent exited with code 1: Traceback (most recent call last):\n  File "/omd/sites/monitoring/local/share/check_mk/agents/special/agent_nextcloud_data", line 129, in <module>\n    print("Version: %s" % data[\'ocs\'][\'data\'][\'nextcloud\'][\'system\'][\'version\'])\nTypeError: list indices must be integers or slices, not str'))`

Would be awesome when you could help me fix this error.

**Comment by matoH12** [comment]
Can you send me output json from API ? https://my.nextcloud.com/ocs/v2.php/apps/serverinfo/api/v1/info  Im interest  version section. For example:
`<system>
<version>24.0.6.1</version>`

**Comment by LordWurstebrot** [comment]
Hi, thanks for your help. 

[nextcloud_api.zip](https://github.com/matoH12/checkmk-nextcloud/files/9797675/nextcloud_api.zip)

I noticed the following error, when viewing the api output:

`Parse error on line 1:
<ocs><meta><status
^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'`

**Comment by matoH12** [comment]
Im see error on first message with "system version" and second is with "status" ?  You use latest version of plugins ? If you can try run check plugin manualy: 
`/omd/sites/h12/local/share/check_mk/agents/special/agent_nextcloud_data -u admin -p pass --no-cert-check data.mhasin.sk`
you use RAW or enterprice version ?

**Comment by LordWurstebrot** [comment]
Version of plugin
![cmk_version_plugin](https://user-images.githubusercontent.com/64687344/196727490-c0e87180-9a4b-413c-ae38-d0bc0af2480c.png)

CMK (free / enterprice) version
![cmk_version](https://user-images.githubusercontent.com/64687344/196727793-ccceb9f7-c0f1-4dc4-9e73-e0681519b27d.png)

Output of your comand
![output_comand](https://user-images.githubusercontent.com/64687344/196727927-244d49d5-3286-4b15-909b-b2d9a9318175.png)

Hope this helps.

**Comment by matoH12** [comment]
Yes im see you dont have installed python module requests. Can you try install this via pip and run special agent again?  command: pip3 install requests

**Comment by LordWurstebrot** [comment]
Now I get the following output:

`<<<check_mk>>>
Traceback (most recent call last):
  File "/omd/sites/monitoring/local/share/check_mk/agents/special/agent_nextcloud_data", line 129, in <module>
    print ("Version: %s" % data['ocs']['data']['nextcloud']['system']['version'])
KeyError: 'nextcloud'
`

**Comment by matoH12** [comment]
Interesting bug. If you open "download agent output" you see correct data from nextcloud ? 
Example:

![data1](https://user-images.githubusercontent.com/63114658/196765786-f26fefc0-1efb-4410-a073-e80efe9971e4.JPG)
![data2](https://user-images.githubusercontent.com/63114658/196765800-8f92d9ab-cad7-4980-8838-8f6cb75149a6.JPG)

**Comment by LordWurstebrot** [comment]
Output:

Fetching 'agent'...
Failed: Failed to fetch data from sub.domain.de: Error(MKFetcherError('Agent exited with code 1: Traceback (most recent call last):\n  File "/omd/sites/monitoring/local/share/check_mk/agents/special/agent_nextcloud_data", line 129, in <module>\n    print("Version: %s" % data[\'ocs\'][\'data\'][\'nextcloud\'][\'system\'][\'version\'])\nKeyError: \'nextcloud\''))

Job finished.

**Comment by LordWurstebrot** [comment]
Are those setting right?
<img width="893" alt="1" src="https://user-images.githubusercontent.com/64687344/196769149-05f93c12-cfb9-4ee6-b6e1-b51d9597f1bc.png">
<img width="893" alt="2" src="https://user-images.githubusercontent.com/64687344/196769160-f2edfddd-724a-434e-a832-bba49852bec1.png">

**Comment by matoH12** [comment]
Can you run special agent manualy again ?  get good output ? So im thing the problem is in username and password ? can you try this commant too:  `curl  -u admin:"password" https://data.mhasin.sk/ocs/v2.php/apps/serverinfo/api/v1/info`

**Comment by matoH12** [comment]
Ok im know where is problem.... Can you specify URL address in  DNS hostname or IP address.  In the default the URL address is read from name of host and you can specify custom URL address for nextcloud.

**Comment by LordWurstebrot** [comment]
> Can you run special agent manualy again ? get good output ? So im thing the problem is in username and password ? can you try this commant too: `curl -u admin:"password" https://data.mhasin.sk/ocs/v2.php/apps/serverinfo/api/v1/info`

![grafik](https://user-images.githubusercontent.com/64687344/196769630-af3b506c-6627-4e82-a7b7-636f96366cec.png)

**Comment by matoH12** [comment]
can you specify this option. Its URL address or IP address of nexcloud server

![obrázok](https://user-images.githubusercontent.com/63114658/196770037-a406d306-45a1-4c27-aff9-fc9a4c05ca02.png)

**Comment by LordWurstebrot** [comment]
Okay I changed it
<img width="893" alt="3" src="https://user-images.githubusercontent.com/64687344/196771797-25ab8842-2043-4db4-8803-0ee0d08bc338.PNG">

but I get the same error:
`Failed: Failed to fetch data from sub.domain.de: Error(MKFetcherError('Agent exited with code 1: Traceback (most recent call last):\n File "/omd/sites/monitoring/local/share/check_mk/agents/special/agent_nextcloud_data", line 129, in \n print("Version: %s" % data['ocs']['data']['nextcloud']['system']['version'])\nKeyError: 'nextcloud''))`

**Comment by matoH12** [comment]
ach :(   So im dont know becouse im saw the variable nextcloud in you CSV you have...  So  can you coment the line `Version: %s" % data['ocs']['data']['nextcloud']['system']['version']` in the special agent file /`omd/sites/monitoring/local/share/check_mk/agents/special/agent_nextcloud_data` and then run again.  In my instalation everything work.  So im saw you use version 1.2.2 can you try 1.2.3  version ?

**Comment by LordWurstebrot** [comment]
I did the update to 1.2.3 and comment line Version: ...

Now I get this error:
`Failed: Failed to fetch data from cloud.domain.de: Error(MKFetcherError("Program '/omd/sites/monitoring/local/share/check_mk/agents/special/agent_nextcloud_data' not found (exit code 127)"))
`

**Comment by matoH12** [comment]
Hi sorry for delay. Im try install clear version och checkmk and nextcloud plugin version 1.2.3 and everything work great. So you try detelete the plugin detele everything files from plugins from system and then install the plugins again.

**Comment by LordWurstebrot** [comment]
Hi no problem. I will do it later today. How is you CMK setup?

I am running CMK in a Ubuntu 22.04 LXD Container on a QNAP NAS. 

Dose the Plugin need any special ports open maybe?

**Comment by matoH12** [comment]
So im try docker version, clear ubuntu virtual  and plugin work. So you need:
1. HTTPS connect to  nextcloud server  (check if you have connect from checkmk to nextcloud via CURL. )
2. admin account what have permission to read data from API on nextcloud
3. in checkmk you need configure admin account as parameter for plugin nextcloud
4. if dont have SSL certificate you can disable certificate verification. 
5. check if you have installed python requests library 

If you can try manualy check if everything work run this command with you parameter (username, password, URL): /omd/sites/h12/local/share/check_mk/agents/special/agent_nextcloud_data -u admin -p pass --no-cert-check data.mhasin.sk

**Comment by LordWurstebrot** [comment]
Hi, sorry for the late answer:

I think the problem is with my nextcloud setup. Because if I load up the serverinfo api in my browser I works fine and I get the values as json output. But if I use CURL (HTTPS) with user and password option I get the following error:

1)  `{"ocs":{"meta":{"status":"failure","statuscode":401,"message":null},"data":{"mes`

2) Yes as I can see it from the browser

3) Yes I did. Its the same user I use in the browser

4) Nextcloud has a SSL certificate but CMK has none because I only access it from my internal network

5) Yes reinstall it to be sure

**Comment by LordWurstebrot** [comment]
I have now reinstalled everything and run the command with my data
`/omd/sites/h12/local/share/check_mk/agents/special/agent_nextcloud_data -u admin -p pass --no-cert-check data.mhasin.sk`

Output:
`/usr/bin/env: ‘python1’: No such file or directory`

I tried to install `python-is-python3` but I get the same Error

**Comment by matoH12** [comment]
interesting because the plugin use python3 no python1 or python2.... Its define in header of file `#!/usr/bin/env python3`  Im develop version 1.2.4 where is bug for RAW version of checkmk... Can you try it ?  The problem report @nate386

**Comment by LordWurstebrot** [comment]
I updated the plugin to 1.2.4. Now I get the following error:

Error shown on terminal:

`<<<check_mk>>>
Traceback (most recent call last):
  File "/omd/sites/monitoring/local/share/check_mk/agents/special/agent_nextclou                                                                             d_data", line 133, in <module>
    print("Version: %s" % data['ocs']['data']['nextcloud']['system']['version'])
KeyError: 'nextcloud'`

Error shown on CMK:

`Error(MKFetcherError('Agent exited with code 1: Traceback (most recent call last):\n  File "/omd/sites/monitoring/local/share/check_mk/agents/special/agent_nextcloud_data", line 133, in <module>\n    print("Version: %s" % data[\'ocs\'][\'data\'][\'nextcloud\'][\'system\'][\'version\'])\nTypeError: list indices must be integers or slices, not str'))
`

I got 2FA enabled for my nextcloud instance. Coud this be a Problem?

**Comment by matoH12** [comment]
Yes the 2FA is not support but in new version im add support for TOKEN authorization. Install version https://github.com/matoH12/checkmk-nextcloud/blob/main/nextcloud-1.3.mkp and set token on nextcloud server `occ config:app:set serverinfo token --value yourtoken`

**Comment by LordWurstebrot** [comment]
Hi, sorry for the late answer. I did as you said but I only get the ping status:
<img width="560" alt="nextcloud_host" src="https://user-images.githubusercontent.com/64687344/200020363-7037eb2b-fecc-4999-a668-f51c769a5057.png">

I use this config:
<img width="210" alt="nextcloud_config" src="https://user-images.githubusercontent.com/64687344/200020490-1d5e0603-cd97-411d-8cb6-bfbe4eebd5ca.png">

Job status:
<img width="570" alt="nextcloud_job" src="https://user-images.githubusercontent.com/64687344/200023623-0677820c-85ed-419b-9736-50d6d408cd87.png">

**Comment by matoH12** [comment]
Hi, interesting what you see after  click download output data ?  You see nextcloud data plugin output

**Comment by LordWurstebrot** [comment]
No, it's just a empty .txt file.
