### ISSUE TITLE
Error precompiling checks for host

### ISSUE THREAD

**Issue by nate386** [matoH12/checkmk-nextcloud#5]
Hello,

first of all thank you for the plugin. Unfortunately, I can not use it properly. As soon as I monitor the nextcloud services, I cannot update pending changes. 
The error code is:
Error running automation call restart (exit code 5), error:
Error precompiling checks for host cloud.infomedia-rostock.de: Cannot find check file nextcloud_data needed for check type nextcloud_data
See image
![image](https://user-images.githubusercontent.com/102666429/197819028-96a83166-ff00-4281-a1a0-3c4fd0193964.png)
The command works: 
/omd/sites/monitoring/local/share/check_mk/agents/special/agent_nextcloud_data -u "my-user" -p "my-passport" --no-cert-check cloud.my-domain.com
![image](https://user-images.githubusercontent.com/102666429/197818958-4acfe667-7a28-480d-96a0-e8a2e2252793.png)

here still my output of cmk --debug -R:
Generating configuration for core (type nagios)...
Precompiling host checks...Cannot find check file nextcloud_data needed for check type nextcloud_data
Traceback (most recent call last):
  File "/omd/sites/monitoring/bin/cmk", line 92, in <module>
    exit_status = modes.call(mode_name, mode_args, opts, args)
  File "/omd/sites/monitoring/lib/python3/cmk/base/modes/__init__.py", line 69, in call
    return handler(*handler_args)
  File "/omd/sites/monitoring/lib/python3/cmk/base/modes/check_mk.py", line 1267, in mode_restart
    cmk.base.core.do_restart(
  File "/omd/sites/monitoring/lib/python3/cmk/base/core.py", line 66, in do_restart
    core_config.do_create_config(core, hosts_to_update=hosts_to_update)
  File "/omd/sites/monitoring/lib/python3/cmk/base/core_config.py", line 309, in do_create_config
    _create_core_config(core, hosts_to_update=hosts_to_update)
  File "/omd/sites/monitoring/lib/python3/cmk/base/core_config.py", line 381, in _create_core_config
    core.create_config(config_path, config_cache, hosts_to_update=hosts_to_update)
  File "/omd/sites/monitoring/lib/python3/cmk/base/core_nagios.py", line 76, in create_config
    self._precompile_hostchecks(config_path)
  File "/omd/sites/monitoring/lib/python3/cmk/base/core_nagios.py", line 94, in _precompile_hostchecks
    _precompile_hostchecks(config_path)
  File "/omd/sites/monitoring/lib/python3/cmk/base/core_nagios.py", line 1076, in _precompile_hostchecks
    host_check = _dump_precompiled_hostcheck(
  File "/omd/sites/monitoring/lib/python3/cmk/base/core_nagios.py", line 1217, in _dump_precompiled_hostcheck
    file_list = sorted(_get_legacy_check_file_names_to_load(needed_legacy_check_plugin_names))
  File "/omd/sites/monitoring/lib/python3/cmk/base/core_nagios.py", line 1413, in _get_legacy_check_file_names_to_load
    raise MKGeneralException(
cmk.utils.exceptions.MKGeneralException: Cannot find check file nextcloud_data needed for check type nextcloud_data
![image](https://user-images.githubusercontent.com/102666429/197819101-bd020d3e-c35e-47a4-96ad-5ff7026a8ad5.png)

Unfortunately I don't know how to fix this error.
I hope you can help me here

with kind regards

**Comment by matoH12** [comment]
Hi what version of plugin you have installed ?   Its RAW version of checkmk ?

**Comment by nate386** [comment]
Hey,

It is the version 1.2.2. from https://exchange.checkmk.com/p/nextcloud and yes it is the Checkmk RAW version.

With kind regards

**Comment by matoH12** [comment]
Can you try plugin version 1.2.4. Im fix bug and for my installation of RAW version plugin work   [nextcloud-1.2.4](https://github.com/matoH12/checkmk-nextcloud/blob/585db3cb72a3123307d34b9a7a0f8b8b115d522b/nextcloud-1.2.4.mkp)

**Comment by nate386** [comment]
Yes, the new version has worked. I have tried it before, but had probably given the wrong address for the download. 

Thanks for the help !
